project:
  type: website
  output-dir: docs

website:
  title: "Baden-520-Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Bayern1090
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



